version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PORT: ${PORT:-8000}
    networks:
      - frame_net

networks:
  frame_net:
    external: true